#!/usr/bin/env bash
# Un-stall Dependabot PRs that rotted on a stale base — CANONICAL, synced from
# tbc-platform-workspace.
#
# Source of truth: scripts/workflow-scripts/dependabot-rebase-stale.sh in
# tbc-platform-workspace. DO NOT edit this file in-repo — change the workspace
# copy and run `make workflows ARGS="--apply"` to roll it out everywhere.
# Called by .github/workflows/dependabot-auto-merge.yml (scheduled job).
#
# WHY THIS EXISTS
# A required check's conclusion is bound to a head SHA: once `ci` fails, nothing
# re-runs it unless the branch moves. So a Dependabot PR that failed for a reason
# since fixed on the default branch sits with auto-merge armed forever. Branch
# protection is deliberately `strict:false` (requiring up-to-date branches would
# re-run CI on every open PR each time the default branch moves), and Dependabot's
# own `rebase-strategy: auto` doesn't cover this — it rebases on *merge conflicts*
# and manifest changes, not on a red check. So we ask for the rebase ourselves.
#
# WHY IT CANNOT LOOP
# Two independent guards, because the first one alone is not enough:
#
#  1. We only nudge a PR whose `ci` FAILED **and** whose base differs from the
#     current default-branch head. A successful rebase makes those match, so a
#     genuinely broken PR is never re-nudged.
#
#  2. But a rebase can FAIL — Dependabot gives up on a conflicted PR — leaving the
#     base stale and guard 1 satisfied again on tomorrow's run. So we also skip any
#     PR we already asked since its current head commit: if our request is newer
#     than the head, the last nudge did not move the branch and repeating it would
#     just be daily noise on a PR that needs a human.
#
# Deliberately left alone:
#   - `ci` pass    — auto-merge will land it on its own.
#   - `ci` pending — a run is in flight; nudging would cancel and restart it.
#   - no `ci` check — nothing to re-run (repos with no PR CI, e.g. homebrew-tap).
#   - base == default-branch head — the failure is real; a human should look.
#   - already nudged since the current head — see guard 2.
#
# A rebase does NOT fix a bump whose generated output needs regenerating (e.g. an
# oapi-codegen bump that changes *.gen.go, which Dependabot never regenerates).
# Those keep failing on a current base, which is exactly when this script stands
# down and leaves them for a human.
#
# Requires: gh (authenticated via GH_TOKEN), GH_REPO set to owner/repo.
set -euo pipefail

# How many open Dependabot PRs to examine. 100 is `gh pr list`'s maximum for a
# single non-paginated call; anything beyond it is reported, never dropped silently.
LIMIT=100

# Resolve the default branch's head SHA. Two REST calls rather than
# `gh repo view --json defaultBranchRef`, which returns only the branch *name* —
# its .target.oid is silently empty, which would make every PR look stale and
# nudge the whole queue. Both values are hard-checked for exactly that reason.
base_branch=$(gh api "repos/$GH_REPO" --jq .default_branch)
[[ -n "$base_branch" ]] || { echo "✗ could not resolve the default branch" >&2; exit 1; }
base_head=$(gh api "repos/$GH_REPO/commits/$base_branch" --jq .sha)
[[ -n "$base_head" ]] || { echo "✗ could not resolve $base_branch's head SHA" >&2; exit 1; }
echo "default branch: $base_branch @ $base_head"

nudged=0
while IFS=$'\t' read -r num base_oid; do
	[[ -n "$num" ]] || continue

	if [[ "$base_oid" == "$base_head" ]]; then
		echo "PR #$num: on current base — leaving alone"
		continue
	fi

	# `gh pr checks` exits non-zero when checks are failing — the very case we
	# care about — so never let its status abort the loop under `set -e`.
	ci=$(gh pr checks "$num" --json name,bucket \
		--jq '[.[] | select(.name == "ci") | .bucket] | first // "none"' 2>/dev/null || true)
	ci="${ci:-none}"

	if [[ "$ci" != "fail" ]]; then
		echo "PR #$num: stale base but ci=$ci — leaving alone"
		continue
	fi

	# Guard 2 (see WHY IT CANNOT LOOP): did we already ask, and the branch never
	# moved? Compare our newest rebase request against the head commit's date. A
	# request NEWER than the head means Dependabot could not act on it (typically a
	# conflict), so asking again every day would just be noise.
	head_date=$(gh api "repos/$GH_REPO/pulls/$num" --jq .head.sha 2>/dev/null |
		xargs -I{} gh api "repos/$GH_REPO/commits/{}" --jq .commit.committer.date 2>/dev/null || true)
	last_ask=$(gh api "repos/$GH_REPO/issues/$num/comments?per_page=100" \
		--jq '[.[] | select(.body | contains("@dependabot rebase")) | .created_at] | last // ""' 2>/dev/null || true)
	if [[ -n "$head_date" && -n "$last_ask" && "$last_ask" > "$head_date" ]]; then
		echo "PR #$num: already asked at $last_ask and the head never moved — leaving for a human"
		continue
	fi

	echo "PR #$num: ci failed on stale base ${base_oid:0:7} — requesting rebase"
	gh pr comment "$num" --body "@dependabot rebase"
	nudged=$((nudged + 1))
done < <(gh pr list --author "app/dependabot" --state open --limit "$LIMIT" \
	--json number,baseRefOid --jq '.[] | [.number, .baseRefOid] | @tsv')

# No silent caps (conventions/ci-performance.md): if a repo ever has more open
# Dependabot PRs than we listed, say so rather than quietly ignoring the tail.
open_total=$(gh pr list --author "app/dependabot" --state open --limit 200 --json number --jq 'length' 2>/dev/null || echo 0)
if [[ "${open_total:-0}" -gt "$LIMIT" ]]; then
	echo "⚠ $open_total open Dependabot PRs exceed the --limit of $LIMIT; $((open_total - LIMIT)) were not examined"
fi

echo "requested $nudged rebase(s)"
