#!/usr/bin/env bash
# Un-stall Dependabot PRs that rotted on a stale base — CANONICAL, synced from
# tbc-platform-workspace.
#
# Source of truth: scripts/workflow-scripts/dependabot-rebase-stale.sh in
# tbc-platform-workspace. DO NOT edit this file in-repo — change the workspace
# copy and run `make workflows ARGS="--apply"` to roll it out everywhere.
# Called by .github/workflows/dependabot-auto-merge.yml (scheduled job).
#
# WHY THIS EXISTS
# A required check's conclusion is bound to a head SHA: once `ci` fails, nothing
# re-runs it unless the branch moves. So a Dependabot PR that failed for a reason
# since fixed on the default branch sits with auto-merge armed forever. Branch
# protection is deliberately `strict:false` (requiring up-to-date branches would
# re-run CI on every open PR each time the default branch moves), and Dependabot's
# own `rebase-strategy: auto` doesn't cover this — it rebases on *merge conflicts*
# and manifest changes, not on a red check. So we ask for the rebase ourselves.
#
# WHY IT CANNOT LOOP
# Two independent guards, because the first one alone is not enough:
#
#  1. We only nudge a PR whose `ci` FAILED **and** whose base differs from the
#     current default-branch head. A successful rebase makes those match, so a
#     genuinely broken PR is never re-nudged.
#
#  2. But a rebase can FAIL — Dependabot gives up on a conflicted PR — leaving the
#     base stale and guard 1 satisfied again on tomorrow's run. So we also skip any
#     PR we already asked since its current head commit: if our request is newer
#     than the head, the last nudge did not move the branch and repeating it would
#     just be daily noise on a PR that needs a human.
#
# Deliberately left alone:
#   - `ci` pass    — auto-merge will land it on its own.
#   - `ci` pending — a run is in flight; nudging would cancel and restart it.
#   - no `ci` check — nothing to re-run (repos with no PR CI, e.g. homebrew-tap).
#   - base == default-branch head — the failure is real; a human should look.
#   - already nudged since the current head — see guard 2.
#
# A rebase does NOT fix a bump whose generated output needs regenerating (e.g. an
# oapi-codegen bump that changes *.gen.go, which Dependabot never regenerates).
# Those keep failing on a current base, which is exactly when this script stands
# down and leaves them for a human.
#
# Requires: gh (authenticated via GH_TOKEN), GH_REPO set to owner/repo.
set -euo pipefail

# Fail with something readable rather than `set -u`'s "unbound variable" — this
# script is meant to be runnable by hand (GH_REPO=owner/repo ./the-script.sh) to
# preview what the scheduled job would do.
: "${GH_REPO:?set GH_REPO=owner/repo (the repository to sweep)}"
command -v gh >/dev/null 2>&1 || { echo "✗ gh is required" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "✗ jq is required" >&2; exit 1; }

# How many open Dependabot PRs to examine. 100 is `gh pr list`'s maximum for a
# single non-paginated call; anything beyond it is reported, never dropped silently.
LIMIT=100

# Resolve the default branch's head SHA. Two REST calls rather than
# `gh repo view --json defaultBranchRef`, which returns only the branch *name* —
# its .target.oid is silently empty, which would make every PR look stale and
# nudge the whole queue. Both values are hard-checked for exactly that reason.
base_branch=$(gh api "repos/$GH_REPO" --jq .default_branch)
[[ -n "$base_branch" ]] || { echo "✗ could not resolve the default branch" >&2; exit 1; }
base_head=$(gh api "repos/$GH_REPO/commits/$base_branch" --jq .sha)
[[ -n "$base_head" ]] || { echo "✗ could not resolve $base_branch's head SHA" >&2; exit 1; }
echo "default branch: $base_branch @ $base_head"

nudged=0
while IFS=$'\t' read -r num base_oid; do
	[[ -n "$num" ]] || continue

	if [[ "$base_oid" == "$base_head" ]]; then
		echo "PR #$num: on current base — leaving alone"
		continue
	fi

	# Match on OUTCOME, never on a check NAMED `ci`. Required contexts differ per
	# repo — tbc-platform requires `ci`; tbc-mcp-server requires `security` and
	# `test`; tbc-api requires `test`, `lint` and `security` — so matching a name
	# makes this sweep a silent no-op wherever the naming differs. Reading the real
	# required-context list needs admin, which the workflow's GITHUB_TOKEN does not
	# have, so ANY failing check counts. Over-triggering is bounded by guard 2 below.
	#
	# `gh pr checks` exits non-zero when checks are failing — the very case we care
	# about — so never let its status abort the loop under `set -e`.
	checks=$(gh pr checks "$num" --json name,bucket 2>/dev/null || true)
	[[ -n "$checks" ]] || checks='[]'
	total=$(jq -r 'length' <<<"$checks" 2>/dev/null || echo 0)
	failing=$(jq -r '[.[] | select(.bucket == "fail") | .name] | join(", ")' <<<"$checks" 2>/dev/null || echo "")
	pending=$(jq -r 'if any(.[]; .bucket == "pending") then "yes" else "no" end' <<<"$checks" 2>/dev/null || echo "no")

	if [[ "${total:-0}" -eq 0 ]]; then
		echo "PR #$num: stale base but no checks to re-run — leaving alone"
		continue
	fi
	if [[ "$pending" == "yes" ]]; then
		echo "PR #$num: stale base but a check is still running — leaving alone"
		continue
	fi
	if [[ -z "$failing" ]]; then
		echo "PR #$num: stale base but all checks pass — leaving alone"
		continue
	fi

	# Guard 2 (see WHY IT CANNOT LOOP): did we already ask, and the branch never
	# moved? Compare our newest rebase request against the head commit's date. A
	# request NEWER than the head means Dependabot could not act on it (typically a
	# conflict), so asking again every day would just be noise.
	#
	# --paginate, because `last` over a single 100-comment page is not the newest
	# comment on a long thread — it is just the newest of the first page.
	head_date=$(gh api "repos/$GH_REPO/pulls/$num" --jq .head.sha 2>/dev/null |
		xargs -I{} gh api "repos/$GH_REPO/commits/{}" --jq .commit.committer.date 2>/dev/null || true)
	last_ask=$(gh api --paginate "repos/$GH_REPO/issues/$num/comments?per_page=100" \
		--jq '.[] | select(.body | contains("@dependabot rebase")) | .created_at' 2>/dev/null | tail -1 || true)
	if [[ -n "$head_date" && -n "$last_ask" && "$last_ask" > "$head_date" ]]; then
		echo "PR #$num: already asked at $last_ask and the head never moved — leaving for a human"
		continue
	fi

	echo "PR #$num: [$failing] failed on stale base ${base_oid:0:7} — requesting rebase"
	gh pr comment "$num" --body "@dependabot rebase"
	nudged=$((nudged + 1))
done < <(gh pr list --author "app/dependabot" --state open --limit "$LIMIT" \
	--json number,baseRefOid --jq '.[] | [.number, .baseRefOid] | @tsv')

# No silent caps (conventions/ci-performance.md): if a repo ever has more open
# Dependabot PRs than we listed, say so rather than quietly ignoring the tail.
# Counted via the paginated search API, NOT another capped `gh pr list` — a count
# that is itself truncated would under-report the very overflow it exists to warn
# about, which is the same silent cap one level up.
# The `|| true` belongs INSIDE the pipeline, on the gh call. Outside it (`$(... ) ||
# echo 0`) a gh failure appends a second value to awk's output ("0\n0"); omitting it
# entirely lets `pipefail` fail the substitution and, under `set -e`, kill the script
# right before the warning it is meant to print. Inside, awk always emits exactly one
# number and a gh outage degrades to "0" instead of an abort.
open_total=$({ gh api --paginate "repos/$GH_REPO/pulls?state=open&per_page=100" \
	--jq '[.[] | select(.user.login == "dependabot[bot]")] | length' 2>/dev/null || true; } |
	awk '{s+=$1} END {print s+0}')
[[ "$open_total" =~ ^[0-9]+$ ]] || open_total=0
if [[ "$open_total" -gt "$LIMIT" ]]; then
	echo "⚠ $open_total open Dependabot PRs exceed the --limit of $LIMIT; $((open_total - LIMIT)) were not examined"
fi

echo "requested $nudged rebase(s)"
