# This file was generated by GoReleaser. DO NOT EDIT.
cask "tbc" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern

      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." unless @github_token

      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.2.1"

  on_macos do
    sha256 "4512ee02213dc7aa286fa2d79b5d4379ea642278c69ffe068252c6420ac45aed"
    url "https://github.com/Two-Bear-Capital/tbc-platform/releases/download/v#{version}/tbc_#{version}_darwin_all.tar.gz",
        verified: "github.com/Two-Bear-Capital/tbc-platform/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
  end

  on_linux do
    on_intel do
      sha256 "9b20d29819a5e8d280a1f1155413e608e56c6733cdf131283dd3df4f4959d374"
      url "https://github.com/Two-Bear-Capital/tbc-platform/releases/download/v#{version}/tbc_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Two-Bear-Capital/tbc-platform/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "99d4d65659d4cf35cd3d59fd37596c615b24821576fb613b7d56f8a28de0c3a4"
      url "https://github.com/Two-Bear-Capital/tbc-platform/releases/download/v#{version}/tbc_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Two-Bear-Capital/tbc-platform/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "tbc"
  desc "Two Bear Capital's platform CLI — Affinity, Standard Metrics, BigQuery."
  homepage "https://cli.twobearcapital.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tbc"
  manpage "man/tbc-about.1"
  manpage "man/tbc-affinity-companies-create.1"
  manpage "man/tbc-affinity-companies-delete.1"
  manpage "man/tbc-affinity-companies-find.1"
  manpage "man/tbc-affinity-companies-get.1"
  manpage "man/tbc-affinity-companies-list.1"
  manpage "man/tbc-affinity-companies-update.1"
  manpage "man/tbc-affinity-companies.1"
  manpage "man/tbc-affinity-fields-create.1"
  manpage "man/tbc-affinity-fields-delete.1"
  manpage "man/tbc-affinity-fields-get.1"
  manpage "man/tbc-affinity-fields-list.1"
  manpage "man/tbc-affinity-fields-options-create.1"
  manpage "man/tbc-affinity-fields-options-delete.1"
  manpage "man/tbc-affinity-fields-options-get.1"
  manpage "man/tbc-affinity-fields-options-update.1"
  manpage "man/tbc-affinity-fields-options.1"
  manpage "man/tbc-affinity-fields.1"
  manpage "man/tbc-affinity-files-get.1"
  manpage "man/tbc-affinity-files-list.1"
  manpage "man/tbc-affinity-files-upload.1"
  manpage "man/tbc-affinity-files.1"
  manpage "man/tbc-affinity-lists-add.1"
  manpage "man/tbc-affinity-lists-create.1"
  manpage "man/tbc-affinity-lists-entries.1"
  manpage "man/tbc-affinity-lists-get.1"
  manpage "man/tbc-affinity-lists-list.1"
  manpage "man/tbc-affinity-lists-remove.1"
  manpage "man/tbc-affinity-lists.1"
  manpage "man/tbc-affinity-notes-create.1"
  manpage "man/tbc-affinity-notes-delete.1"
  manpage "man/tbc-affinity-notes-get.1"
  manpage "man/tbc-affinity-notes-list.1"
  manpage "man/tbc-affinity-notes-update.1"
  manpage "man/tbc-affinity-notes.1"
  manpage "man/tbc-affinity-people-create.1"
  manpage "man/tbc-affinity-people-delete.1"
  manpage "man/tbc-affinity-people-find.1"
  manpage "man/tbc-affinity-people-get.1"
  manpage "man/tbc-affinity-people-list.1"
  manpage "man/tbc-affinity-people-update.1"
  manpage "man/tbc-affinity-people.1"
  manpage "man/tbc-affinity.1"
  manpage "man/tbc-auth-login.1"
  manpage "man/tbc-auth-logout.1"
  manpage "man/tbc-auth-status.1"
  manpage "man/tbc-auth-whoami.1"
  manpage "man/tbc-auth.1"
  manpage "man/tbc-bq-query.1"
  manpage "man/tbc-bq.1"
  manpage "man/tbc-completion-bash.1"
  manpage "man/tbc-completion-fish.1"
  manpage "man/tbc-completion-powershell.1"
  manpage "man/tbc-completion-zsh.1"
  manpage "man/tbc-completion.1"
  manpage "man/tbc-config-get.1"
  manpage "man/tbc-config-list.1"
  manpage "man/tbc-config-set.1"
  manpage "man/tbc-config.1"
  manpage "man/tbc-data-affinity-companies-list.1"
  manpage "man/tbc-data-affinity-companies.1"
  manpage "man/tbc-data-company-metrics-list.1"
  manpage "man/tbc-data-company-metrics.1"
  manpage "man/tbc-data-hygiene-domain-reachability-list.1"
  manpage "man/tbc-data-hygiene-domain-reachability.1"
  manpage "man/tbc-data-hygiene-duplicate-domain-list.1"
  manpage "man/tbc-data-hygiene-duplicate-domain.1"
  manpage "man/tbc-data-hygiene-invalid-name-list.1"
  manpage "man/tbc-data-hygiene-invalid-name.1"
  manpage "man/tbc-data-hygiene-missing-domain-list.1"
  manpage "man/tbc-data-hygiene-missing-domain.1"
  manpage "man/tbc-data-portfolio-companies-list.1"
  manpage "man/tbc-data-portfolio-companies.1"
  manpage "man/tbc-data-sm-companies-list.1"
  manpage "man/tbc-data-sm-companies.1"
  manpage "man/tbc-data.1"
  manpage "man/tbc-doctor.1"
  manpage "man/tbc-feedback-bug.1"
  manpage "man/tbc-feedback-feature.1"
  manpage "man/tbc-feedback.1"
  manpage "man/tbc-logs-bundle.1"
  manpage "man/tbc-logs-open.1"
  manpage "man/tbc-logs-path.1"
  manpage "man/tbc-logs-tail.1"
  manpage "man/tbc-logs.1"
  manpage "man/tbc-version.1"
  manpage "man/tbc.1"

  generate_completions_from_executable "bin/tbc", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
